import fs from 'fs';
import fetch from 'node-fetch';
import dijkstra from 'dijkstrajs';
import path from 'path';
import { exec } from 'child_process';

import { overpassUrl, query } from './query.js';
import { 
  buildGraphForDijkstra, 
  findNearestNode, 
  areConnected, 
  findConnectedComponents,
  extractRouteMetadata 
} from './utils/graph.js';
import { buildGeoJSONPath, buildDetailedGeoJSON } from './utils/geojson.js';
import { haversineDistance } from './utils/haversine.js';
import { evaluateRoute, bikeTypes } from './utils/bikeRules.js';

/**
 * Zapisuje GeoJSON do GitHub Gist i otwiera w geojson.io
 */
async function openInGeojsonIO(geojsonData) {
  console.log('\nPrzygotowuję trasę do wyświetlenia w geojson.io...');
  
  try {
    // Utwórz anonimowy Gist
    const gistResponse = await fetch('https://api.github.com/gists', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'BikeRouteApp'
      },
      body: JSON.stringify({
        description: 'Bike route generated by route planner',
        public: true,
        files: {
          'route.geojson': {
            content: JSON.stringify(geojsonData, null, 2)
          }
        }
      })
    });

    if (!gistResponse.ok) {
      throw new Error(`GitHub API error: ${gistResponse.statusText}`);
    }

    const gistData = await gistResponse.json();
    const gistId = gistData.id;
    const rawUrl = gistData.files['route.geojson'].raw_url;
    
    // Utwórz URL do geojson.io z linkiem do Gist
    const geojsonIOUrl = `https://geojson.io/#id=gist:anonymous/${gistId}`;
    
    console.log('    GeoJSON zapisany jako GitHub Gist');
    console.log(`    Gist ID: ${gistId}`);
    console.log(`    Raw URL: ${rawUrl}`);

    
    // Próba otwarcia w przeglądarce
    const command = process.platform === 'win32' ? 'start ""' :
                    process.platform === 'darwin' ? 'open' : 'xdg-open';
    
    exec(`${command} "${geojsonIOUrl}"`, (error) => {
      if (error) {
        console.log('   INSTRUKCJA:');
        console.log('   Ctrl+Click (Windows/Linux) lub Cmd+Click (Mac) na link powyżej');
        console.log('   Lub skopiuj link i wklej w przeglądarce\n');
      }
    });

  } catch (error) {
    console.log('   Nie udało się użyć GitHub Gist API');
    console.log(`   ℹSzczegóły: ${error.message}`);
    console.log('   Alternatywne rozwiązanie: Zapisuję do pliku lokalnego\n');
    
    // Fallback - zapisz lokalnie i pokaż instrukcję
    const outputPath = path.join(process.cwd(), 'route_for_geojson_io.geojson');
    fs.writeFileSync(outputPath, JSON.stringify(geojsonData, null, 2));
    console.log(`   Zapisano do: ${outputPath}`);
    console.log('\n   ╔════════════════════════════════════════════════════════╗');
    console.log('   ║    JAK WYŚWIETLIĆ TRASĘ W GEOJSON.IO                 ║');
    console.log('   ╚════════════════════════════════════════════════════════╝\n');
    console.log('   Metoda 1 (zalecana):');
    console.log('   1. Otwórz \x1b[36mhttps://geojson.io\x1b[0m');
    console.log('   2. Przeciągnij plik "route_for_geojson_io.geojson" na mapę');
    console.log('\n   Metoda 2:');
    console.log('   1. Otwórz \x1b[36mhttps://geojson.io\x1b[0m');
    console.log('   2. Kliknij "Open" → "File"');
    console.log('   3. Wybierz plik "route_for_geojson_io.geojson"\n');
  }
}

async function main() {
  try {

    // KONFIGURACJA 
    const bikeType = 'szosowy'; // Opcje: 'miejski', 'trekkingowy', 'górski', 'szosowy'
    const saveToFile = true; // Czy dodatkowo zapisać do pliku
    const openInBrowser = true; // Czy otworzyć w geojson.io
    
    // Współrzędne start i meta
    const startLat = 51.46681902975696;
    const startLon = 19.571030370525943;
    const endLat = 51.46722369065393;
    const endLon = 19.601921146542217;

    console.log(`\n${'='.repeat(60)}`);
    console.log(`🚴 PLANOWANIE TRASY ROWEROWEJ`);
    console.log(`${'='.repeat(60)}`);
    console.log(`Typ roweru: ${bikeType}`);
    console.log(`Start: ${startLat}, ${startLon}`);
    console.log(`Meta:  ${endLat}, ${endLon}`);
    console.log(`${'='.repeat(60)}\n`);

    // KROK 1: Pobierz dane z Overpass API
    console.log(' KROK 1: Pobieram dane z Overpass API...');
    const response = await fetch(overpassUrl, {
      method: 'POST',
      body: query,
      headers: { 'Content-Type': 'text/plain' },
    });

    if (!response.ok) {
      throw new Error(`Błąd pobierania: ${response.statusText}`);
    }

    const osmData = await response.json();
    console.log('    Dane OSM pobrane pomyślnie');
    console.log(`    Elementów: ${osmData.elements.length}\n`);

    // KROK 2: Buduj graf z metadanymi
    console.log(' KROK 2: Buduję graf z metadanymi...');
    const { nodes, graph, wayMetadata } = buildGraphForDijkstra(osmData);
    console.log(`    Graf zbudowany`);
    console.log(`    Węzłów: ${nodes.size}`);
    console.log(`    Krawędzi: ${Object.keys(graph).length}\n`);

    // KROK 3: Znajdź najbliższe węzły
    console.log('🎯 KROK 3: Szukam najbliższych węzłów...');
    const startNode = findNearestNode(startLat, startLon, nodes);
    const endNode = findNearestNode(endLat, endLon, nodes);

    if (!startNode || !endNode) {
      console.log('    Nie znaleziono węzłów start/meta.');
      return;
    }

    console.log(`    Węzeł startowy: ${startNode}`);
    console.log(`    Węzeł końcowy: ${endNode}\n`);

    // KROK 4: Sprawdź składowe spójne
    const startKey = String(startNode);
    const endKey = String(endNode);
    
    console.log(' KROK 4: Analiza składowych spójnych...');
    const components = findConnectedComponents(graph);
    console.log(`    Graf ma ${components.length} składowych spójnych`);
    
    let startComponent = -1;
    let endComponent = -1;
    
    for (let i = 0; i < components.length; i++) {
      if (components[i].has(startKey)) startComponent = i;
      if (components[i].has(endKey)) endComponent = i;
    }

    if (startComponent !== endComponent) {
      console.log('\n    Węzły są w różnych składowych spójnych!');
      return;
    }

    console.log('    Węzły są w tej samej składowej spójnej\n');

    // KROK 5: Oblicz trasę (Dijkstra)
    console.log('  KROK 5: Obliczam najkrótszą trasę...');
    const pathNodes = dijkstra.find_path(graph, startKey, endKey);

    if (!pathNodes || pathNodes.length === 0) {
      console.log('    Nie znaleziono trasy.');
      return;
    }

    console.log(`    Znaleziono trasę!`);
    console.log(`    Trasa zawiera ${pathNodes.length} węzłów\n`);

    // KROK 6: Oblicz długość trasy
    console.log(' KROK 6: Obliczam długość trasy...');
    let totalDistance = 0;
    for (let i = 0; i < pathNodes.length - 1; i++) {
      const a = nodes.get(parseInt(pathNodes[i]));
      const b = nodes.get(parseInt(pathNodes[i + 1]));
      totalDistance += haversineDistance(a.lat, a.lon, b.lat, b.lon);
    }

    console.log(`    Długość trasy: ${(totalDistance / 1000).toFixed(3)} km\n`);

    // KROK 7: Wydobądź metadane trasy
    console.log(' KROK 7: Analizuję nawierzchnię...');
    const routeMetadata = extractRouteMetadata(pathNodes, wayMetadata);
    
    const uniqueSurfaces = [...new Set(routeMetadata.surfaces)];
    console.log(`    Nawierzchnie: ${uniqueSurfaces.join(', ')}\n`);

    // KROK 8: Oceń trasę
    console.log('  KROK 8: Oceniam trasę...');
    const evaluation = evaluateRoute(routeMetadata.surfaces, bikeType);
    console.log(`   ${evaluation.message}\n`);

    // KROK 9: Przygotuj GeoJSON
    console.log('📦 KROK 9: Przygotowuję GeoJSON...');
    const routeGeoJSON = buildGeoJSONPath(
      pathNodes, 
      nodes, 
      totalDistance, 
      routeMetadata, 
      bikeType, 
      evaluation
    );

    // Opcjonalnie zapisz do pliku
    if (saveToFile) {
      const outputPath = path.join(process.cwd(), 'route_output.geojson');
      fs.writeFileSync(outputPath, JSON.stringify(routeGeoJSON, null, 2));
      console.log('   ✅ Zapisano do route_output.geojson');
    }

    // KROK 10: Otwórz w geojson.io
    if (openInBrowser) {
      openInGeojsonIO(routeGeoJSON);
    }

    // PODSUMOWANIE
    console.log(`\n${'='.repeat(60)}`);
    console.log(' GOTOWE! Podsumowanie:');
    console.log(`${'='.repeat(60)}`);
    console.log(` Typ roweru:        ${bikeType}`);
    console.log(` Długość trasy:     ${(totalDistance / 1000).toFixed(3)} km`);
    console.log(` Węzłów na trasie:  ${pathNodes.length}`);
    console.log(`  Nawierzchnie:      ${uniqueSurfaces.join(', ')}`);
    console.log(`${evaluation.status === 'success' ? '✅' : evaluation.status === 'warning' ? '⚠️' : '❌'} Status:            ${evaluation.status.toUpperCase()}`);
    console.log(`${'='.repeat(60)}\n`);

  } catch (err) {
    console.error('\n BŁĄD:', err.message);
    console.error('Stack trace:', err.stack);
  }
}

main();